/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulador;

import java.util.regex.Pattern;

/**
 *
 * Larissa Fogaça Mendes       nº120147
 * Pedro Maschio Portes        nº120137
 * Thalita Martins Yamatsuka   nº120126
 * 
 */

public class Principal extends javax.swing.JFrame {

    Memoria mem;
    Ula ul;
    Unidade_controle uc;
    Registrador[] registra;
    int tamanho = 0;
    Registrador reg0;
    Registrador reg1;
    Registrador reg2;
    Registrador reg3;
    Registrador reg4;
    Registrador reg5;
    Registrador reg6;
    Registrador reg7;
    Registrador reg8;
    Registrador reg9;
    Registrador reg10;
    Registrador reg11;
    Registrador reg12;
    Registrador reg13;
    Registrador reg14;
    Registrador reg15;
    Registrador reg16;
    Registrador reg17;
    Registrador reg18;
    Registrador reg19;
    Registrador reg20;
    Registrador reg21;
    Registrador reg22;
    Registrador reg23;
    Registrador reg24;
    Registrador reg25;
    Registrador reg26;
    Registrador reg27;
    Registrador reg28;
    Registrador reg29;
    Registrador reg30;
    Registrador reg31;

    /**
     * Creates new form Principal
     */
    public Principal() {
        registra = new Registrador[32];
        mem = new Memoria();
        ul = new Ula();
        uc = new Unidade_controle(mem);
        reg0 = new Registrador("reg0", mem);
        reg1 = new Registrador("reg1", mem);
        reg2 = new Registrador("reg2", mem);
        reg3 = new Registrador("reg3", mem);
        reg4 = new Registrador("reg4", mem);
        reg5 = new Registrador("reg5", mem);
        reg6 = new Registrador("reg6", mem);
        reg7 = new Registrador("reg7", mem);
        reg8 = new Registrador("reg8", mem);
        reg9 = new Registrador("reg9", mem);
        reg10 = new Registrador("reg10", mem);
        reg11 = new Registrador("reg11", mem);
        reg12 = new Registrador("reg12", mem);
        reg13 = new Registrador("reg13", mem);
        reg14 = new Registrador("reg14", mem);
        reg15 = new Registrador("reg15", mem);
        reg16 = new Registrador("reg16", mem);
        reg17 = new Registrador("reg17", mem);
        reg18 = new Registrador("reg18", mem);
        reg19 = new Registrador("reg19", mem);
        reg20 = new Registrador("reg20", mem);
        reg21 = new Registrador("reg21", mem);
        reg22 = new Registrador("reg22", mem);
        reg23 = new Registrador("reg23", mem);
        reg24 = new Registrador("reg24", mem);
        reg25 = new Registrador("reg25", mem);
        reg26 = new Registrador("reg26", mem);
        reg27 = new Registrador("reg27", mem);
        reg28 = new Registrador("reg28", mem);
        reg29 = new Registrador("reg29", mem);
        reg30 = new Registrador("reg30", mem);
        reg31 = new Registrador("reg31", mem);

        registra[0] = reg0;
        registra[1] = reg1;
        registra[2] = reg2;
        registra[3] = reg3;
        registra[4] = reg4;
        registra[5] = reg5;
        registra[6] = reg6;
        registra[7] = reg7;
        registra[8] = reg8;
        registra[9] = reg9;
        registra[10] = reg10;
        registra[11] = reg11;
        registra[12] = reg12;
        registra[13] = reg13;
        registra[14] = reg14;
        registra[15] = reg15;
        registra[16] = reg16;
        registra[17] = reg17;
        registra[18] = reg18;
        registra[19] = reg19;
        registra[20] = reg20;
        registra[21] = reg21;
        registra[22] = reg22;
        registra[23] = reg23;
        registra[24] = reg24;
        registra[25] = reg25;
        registra[26] = reg26;
        registra[27] = reg27;
        registra[28] = reg28;
        registra[29] = reg29;
        registra[30] = reg30;
        registra[31] = reg31;

        initComponents();

        mem.escrita(0, 10);
        mem.escrita(1, 20);
        mem.escrita(2, 30);
        mem.escrita(3, 40);

        atualizar_Registradores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void atualizar_Registradores() {
        jTextField1.setText("" + registra[0].dado());
        jTextField2.setText("" + registra[1].dado());
        jTextField3.setText("" + registra[2].dado());
        jTextField4.setText("" + registra[3].dado());
        jTextField5.setText("" + registra[4].dado());
        jTextField6.setText("" + registra[5].dado());
        jTextField8.setText("" + registra[6].dado());
        jTextField7.setText("" + registra[7].dado());
        jTextField9.setText("" + registra[8].dado());
        jTextField10.setText("" + registra[9].dado());
        jTextField13.setText("" + registra[10].dado());
        jTextField12.setText("" + registra[11].dado());
        jTextField11.setText("" + registra[12].dado());
        jTextField15.setText("" + registra[13].dado());
        jTextField14.setText("" + registra[14].dado());
        jTextField17.setText("" + registra[15].dado());
        jTextField16.setText("" + registra[16].dado());
        jTextField19.setText("" + registra[17].dado());
        jTextField18.setText("" + registra[18].dado());
        jTextField21.setText("" + registra[19].dado());
        jTextField20.setText("" + registra[20].dado());
        jTextField22.setText("" + registra[21].dado());
        jTextField23.setText("" + registra[22].dado());
        jTextField24.setText("" + registra[23].dado());
        jTextField25.setText("" + registra[24].dado());
        jTextField26.setText("" + registra[25].dado());
        jTextField27.setText("" + registra[26].dado());
        jTextField28.setText("" + registra[27].dado());
        jTextField29.setText("" + registra[28].dado());
        jTextField30.setText("" + registra[29].dado());
        jTextField31.setText("" + registra[30].dado());
        jTextField32.setText("" + registra[31].dado());
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRegistrador = new javax.swing.JPanel();
        jLabelRegistrador = new javax.swing.JLabel();
        jLabelR1 = new javax.swing.JLabel();
        jLabelR2 = new javax.swing.JLabel();
        jLabelR3 = new javax.swing.JLabel();
        jLabelR4 = new javax.swing.JLabel();
        jLabelR5 = new javax.swing.JLabel();
        jLabelR6 = new javax.swing.JLabel();
        jLabelR7 = new javax.swing.JLabel();
        jLabelR8 = new javax.swing.JLabel();
        jLabelR9 = new javax.swing.JLabel();
        jLabelR10 = new javax.swing.JLabel();
        jLabelR12 = new javax.swing.JLabel();
        jLabelR13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabelR11 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabelR14 = new javax.swing.JLabel();
        jLabelR15 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabelR16 = new javax.swing.JLabel();
        jLabelR17 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jLabelR18 = new javax.swing.JLabel();
        jLabelR19 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jLabelR20 = new javax.swing.JLabel();
        jLabelR21 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabelR22 = new javax.swing.JLabel();
        jLabelR23 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabelR24 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabelR25 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabelR26 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabelR27 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabelR28 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabelR29 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabelR30 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jLabelR31 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jLabelR32 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jPanelInstrucao = new javax.swing.JPanel();
        jLabelInstrucao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_instrucao = new javax.swing.JTextArea();
        btnDecodificar = new javax.swing.JButton();
        btnatualiza = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelRegistrador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelRegistrador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabelRegistrador.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelRegistrador.setText("Registradores");

        jLabelR1.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR1.setText("R1:");

        jLabelR2.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR2.setText("R2:");

        jLabelR3.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR3.setText("R3:");

        jLabelR4.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR4.setText("R4:");

        jLabelR5.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR5.setText("R5:");

        jLabelR6.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR6.setText("R6:");

        jLabelR7.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR7.setText("R7:");

        jLabelR8.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR8.setText("R8:");

        jLabelR9.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR9.setText("R9:");

        jLabelR10.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR10.setText("R10:");

        jLabelR12.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR12.setText("R12:");

        jLabelR13.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR13.setText("R13:");

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setText("0");

        jTextField3.setEditable(false);
        jTextField3.setText("0");

        jTextField4.setEditable(false);
        jTextField4.setText("0");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.setText("0");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.setEditable(false);
        jTextField6.setText("0");

        jTextField7.setEditable(false);
        jTextField7.setText("0");

        jTextField8.setEditable(false);
        jTextField8.setText("0");

        jTextField9.setEditable(false);
        jTextField9.setText("0");

        jTextField10.setEditable(false);
        jTextField10.setText("0");

        jTextField11.setEditable(false);
        jTextField11.setText("0");

        jTextField12.setEditable(false);
        jTextField12.setText("0");

        jTextField13.setEditable(false);
        jTextField13.setText("0");

        jLabelR11.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR11.setText("R11:");

        jTextField14.setEditable(false);
        jTextField14.setText("0");

        jTextField15.setEditable(false);
        jTextField15.setText("0");

        jLabelR14.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR14.setText("R14:");

        jLabelR15.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR15.setText("R15:");

        jTextField16.setEditable(false);
        jTextField16.setText("0");

        jTextField17.setEditable(false);
        jTextField17.setText("0");

        jLabelR16.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR16.setText("R16:");

        jLabelR17.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR17.setText("R17:");

        jTextField18.setEditable(false);
        jTextField18.setText("0");

        jTextField19.setEditable(false);
        jTextField19.setText("0");

        jLabelR18.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR18.setText("R18:");

        jLabelR19.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR19.setText("R19:");

        jTextField20.setEditable(false);
        jTextField20.setText("0");

        jTextField21.setEditable(false);
        jTextField21.setText("0");

        jLabelR20.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR20.setText("R20:");

        jLabelR21.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR21.setText("R21:");

        jTextField22.setEditable(false);
        jTextField22.setText("0");

        jLabelR22.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR22.setText("R22:");

        jLabelR23.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR23.setText("R23:");

        jTextField23.setEditable(false);
        jTextField23.setText("0");

        jLabelR24.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR24.setText("R24:");

        jTextField24.setEditable(false);
        jTextField24.setText("0");

        jLabelR25.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR25.setText("R25:");

        jTextField25.setEditable(false);
        jTextField25.setText("0");

        jLabelR26.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR26.setText("R26:");

        jTextField26.setEditable(false);
        jTextField26.setText("0");

        jLabelR27.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR27.setText("R27:");

        jTextField27.setEditable(false);
        jTextField27.setText("0");

        jLabelR28.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR28.setText("R28:");

        jTextField28.setEditable(false);
        jTextField28.setText("0");

        jLabelR29.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR29.setText("R29:");

        jTextField29.setEditable(false);
        jTextField29.setText("0");

        jLabelR30.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR30.setText("R30:");

        jTextField30.setEditable(false);
        jTextField30.setText("0");

        jLabelR31.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR31.setText("R31:");

        jTextField31.setEditable(false);
        jTextField31.setText("0");

        jLabelR32.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        jLabelR32.setText("R32:");

        jTextField32.setEditable(false);
        jTextField32.setText("0");

        javax.swing.GroupLayout jPanelRegistradorLayout = new javax.swing.GroupLayout(jPanelRegistrador);
        jPanelRegistrador.setLayout(jPanelRegistradorLayout);
        jPanelRegistradorLayout.setHorizontalGroup(
            jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField7))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField8))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField9))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField10))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField13))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField12))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField11))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField15))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField14))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField17)))
                        .addGap(51, 51, 51)
                        .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField21))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField20))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField22))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField23))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField24))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField25))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField26))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField27))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField28))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField29))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField30))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField31))
                            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                                .addComponent(jLabelR32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField32))))
                    .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabelRegistrador)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanelRegistradorLayout.setVerticalGroup(
            jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRegistrador)
                .addGap(27, 27, 27)
                .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                        .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelR1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelR2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                        .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelR17)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelR18)
                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelR3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelR19)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelR4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelR20)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelR5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelR21)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelR6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelR22)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelR7)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelRegistradorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelR23)
                            .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelR8)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelR24)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelR9)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelR25)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelR10)
                    .addComponent(jLabelR26)
                    .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelR11)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelR27)
                    .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelR12)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelR28)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelR13)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelR29)
                    .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelR14)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelR30)
                    .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelR15)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelR31)
                    .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelR16)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelR32)
                    .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanelInstrucao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelInstrucao.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelInstrucao.setText("Instruções");

        txt_instrucao.setColumns(20);
        txt_instrucao.setRows(5);
        jScrollPane1.setViewportView(txt_instrucao);

        btnDecodificar.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        btnDecodificar.setText("Decodificar");
        btnDecodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecodificarActionPerformed(evt);
            }
        });

        btnatualiza.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 14)); // NOI18N
        btnatualiza.setText("Atualizar Registradores");
        btnatualiza.setActionCommand("Decodificar");
        btnatualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatualizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInstrucaoLayout = new javax.swing.GroupLayout(jPanelInstrucao);
        jPanelInstrucao.setLayout(jPanelInstrucaoLayout);
        jPanelInstrucaoLayout.setHorizontalGroup(
            jPanelInstrucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInstrucaoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabelInstrucao)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelInstrucaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInstrucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(btnDecodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelInstrucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelInstrucaoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnatualiza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelInstrucaoLayout.setVerticalGroup(
            jPanelInstrucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInstrucaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInstrucao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addGap(79, 79, 79)
                .addComponent(btnDecodificar)
                .addContainerGap())
            .addGroup(jPanelInstrucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInstrucaoLayout.createSequentialGroup()
                    .addContainerGap(240, Short.MAX_VALUE)
                    .addComponent(btnatualiza)
                    .addGap(45, 45, 45)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRegistrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelInstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRegistrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelInstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnDecodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecodificarActionPerformed

        String instrucoes = txt_instrucao.getText();

        String instrucao[] = instrucoes.split(Pattern.quote(";"));

        if (instrucao[0].equals("load")) {
            uc.interpretador(instrucao[0], registra[Integer.parseInt(instrucao[1])], Integer.parseInt(instrucao[2]));
            instrucao[0] = null;
            instrucao[1] = null;
            instrucao[2] = null;
        } else if (instrucao[0].equals("add")) {
            uc.interpretador(instrucao[0], registra[Integer.parseInt(instrucao[1])], registra[Integer.parseInt(instrucao[2])], registra[Integer.parseInt(instrucao[3])]);
            instrucao[0] = null;
            instrucao[1] = null;
            instrucao[2] = null;
            instrucao[3] = null;
        } else if (instrucao[0].equals("sub")) {
            uc.interpretador(instrucao[0], registra[Integer.parseInt(instrucao[1])], registra[Integer.parseInt(instrucao[2])], registra[Integer.parseInt(instrucao[3])]);
            instrucao[0] = null;
            instrucao[1] = null;
            instrucao[2] = null;
            instrucao[3] = null;
        } else if (instrucao[0].equals("mult")) {
            uc.interpretador(instrucao[0], registra[Integer.parseInt(instrucao[1])], registra[Integer.parseInt(instrucao[2])], registra[Integer.parseInt(instrucao[3])]);
            instrucao[0] = null;
            instrucao[1] = null;
            instrucao[2] = null;
            instrucao[3] = null;
        } else if (instrucao[0].equals("div")) {
            uc.interpretador(instrucao[0], registra[Integer.parseInt(instrucao[1])], registra[Integer.parseInt(instrucao[2])], registra[Integer.parseInt(instrucao[3])]);
            instrucao[0] = null;
            instrucao[1] = null;
            instrucao[2] = null;
            instrucao[3] = null;
        }
        atualizar_Registradores();
    }//GEN-LAST:event_btnDecodificarActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void btnatualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatualizaActionPerformed
        // TODO add your handling code here:
        jTextField32.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
        jTextField18.setText("");
        jTextField19.setText("");
        jTextField20.setText("");
        jTextField21.setText("");
        jTextField22.setText("");
        txt_instrucao.setText("");
        jTextField23.setText("");
        jTextField24.setText("");
        jTextField25.setText("");
        jTextField26.setText("");
        jTextField28.setText("");
        jTextField27.setText("");
        jTextField28.setText("");
        jTextField29.setText("");
        jTextField30.setText("");
        jTextField31.setText("");
        
        
        
    }//GEN-LAST:event_btnatualizaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecodificar;
    private javax.swing.JButton btnatualiza;
    private javax.swing.JLabel jLabelInstrucao;
    private javax.swing.JLabel jLabelR1;
    private javax.swing.JLabel jLabelR10;
    private javax.swing.JLabel jLabelR11;
    private javax.swing.JLabel jLabelR12;
    private javax.swing.JLabel jLabelR13;
    private javax.swing.JLabel jLabelR14;
    private javax.swing.JLabel jLabelR15;
    private javax.swing.JLabel jLabelR16;
    private javax.swing.JLabel jLabelR17;
    private javax.swing.JLabel jLabelR18;
    private javax.swing.JLabel jLabelR19;
    private javax.swing.JLabel jLabelR2;
    private javax.swing.JLabel jLabelR20;
    private javax.swing.JLabel jLabelR21;
    private javax.swing.JLabel jLabelR22;
    private javax.swing.JLabel jLabelR23;
    private javax.swing.JLabel jLabelR24;
    private javax.swing.JLabel jLabelR25;
    private javax.swing.JLabel jLabelR26;
    private javax.swing.JLabel jLabelR27;
    private javax.swing.JLabel jLabelR28;
    private javax.swing.JLabel jLabelR29;
    private javax.swing.JLabel jLabelR3;
    private javax.swing.JLabel jLabelR30;
    private javax.swing.JLabel jLabelR31;
    private javax.swing.JLabel jLabelR32;
    private javax.swing.JLabel jLabelR4;
    private javax.swing.JLabel jLabelR5;
    private javax.swing.JLabel jLabelR6;
    private javax.swing.JLabel jLabelR7;
    private javax.swing.JLabel jLabelR8;
    private javax.swing.JLabel jLabelR9;
    private javax.swing.JLabel jLabelRegistrador;
    private javax.swing.JPanel jPanelInstrucao;
    private javax.swing.JPanel jPanelRegistrador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextArea txt_instrucao;
    // End of variables declaration//GEN-END:variables
}
